INSERT INTO stations (StationId, StationName, City, State, Status) VALUES ('AP001', 'Secretariat, Amaravati - APPCB', 'Amaravati', 'Andhra Pradesh', 
            'Active'), ('AP002', 'Anand Kala Kshetram, Rajamahendravaram - APPCB', 'Rajamahendravaram', 'Andhra Pradesh', 
            'None'), ('AP003', 'Tirumala, Tirupati - APPCB', 'Tirupati', 'Andhra Pradesh', 
            'None'), ('AP004', 'PWD Grounds, Vijayawada - APPCB', 'Vijayawada', 'Andhra Pradesh', 
            'None'), ('AP005', 'GVM Corporation, Visakhapatnam - APPCB', 'Visakhapatnam', 'Andhra Pradesh', 
            'Active'), ('AS001', 'Railway Colony, Guwahati - APCB', 'Guwahati', 'Assam', 
            'Active'), ('BR001', 'Collectorate, Gaya - BSPCB', 'Gaya', 'Bihar', 
            'None'), ('BR002', 'SFTI Kusdihra, Gaya - BSPCB', 'Gaya', 'Bihar', 
            'None'), ('BR003', 'Industrial Area, Hajipur - BSPCB', 'Hajipur', 'Bihar', 
            'None'), ('BR004', 'Muzaffarpur Collectorate, Muzaffarpur - BSPCB', 'Muzaffarpur', 'Bihar', 
            'None'), ('BR005', 'DRM Office Danapur, Patna - BSPCB', 'Patna', 'Bihar', 
            'Active'), ('BR006', 'Govt. High School Shikarpur, Patna - BSPCB', 'Patna', 'Bihar', 
            'Active'), ('BR007', 'IGSC Planetarium Complex, Patna - BSPCB', 'Patna', 'Bihar', 
            'Active'), ('BR008', 'Muradpur, Patna - BSPCB', 'Patna', 'Bihar', 
            'Active'), ('BR009', 'Rajbansi Nagar, Patna - BSPCB', 'Patna', 'Bihar', 
            'Active'), ('BR010', 'Samanpura, Patna - BSPCB', 'Patna', 'Bihar', 
            'Active'), ('CH001', 'Sector-25, Chandigarh - CPCC', 'Chandigarh', 'Chandigarh', 
            'Active'), ('DL001', 'Alipur, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL002', 'Anand Vihar, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL003', 'Ashok Vihar, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL004', 'Aya Nagar, Delhi - IMD', 'Delhi', 'Delhi', 
            'Active'), ('DL005', 'Bawana, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL006', 'Burari Crossing, Delhi - IMD', 'Delhi', 'Delhi', 
            'Inactive'), ('DL007', 'CRRI Mathura Road, Delhi - IMD', 'Delhi', 'Delhi', 
            'Active'), ('DL008', 'DTU, Delhi - CPCB', 'Delhi', 'Delhi', 
            'Active'), ('DL009', 'Dr. Karni Singh Shooting Range, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL010', 'Dwarka-Sector 8, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL011', 'East Arjun Nagar, Delhi - CPCB', 'Delhi', 'Delhi', 
            'Active'), ('DL012', 'IGI Airport (T3), Delhi - IMD', 'Delhi', 'Delhi', 
            'Active'), ('DL013', 'IHBAS, Dilshad Garden, Delhi - CPCB', 'Delhi', 'Delhi', 
            'Active'), ('DL014', 'ITO, Delhi - CPCB', 'Delhi', 'Delhi', 
            'Active'), ('DL015', 'Jahangirpuri, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL016', 'Jawaharlal Nehru Stadium, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL017', 'Lodhi Road, Delhi - IMD', 'Delhi', 'Delhi', 
            'Active'), ('DL018', 'Major Dhyan Chand National Stadium, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL019', 'Mandir Marg, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL020', 'Mundka, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL021', 'NSIT Dwarka, Delhi - CPCB', 'Delhi', 'Delhi', 
            'Active'), ('DL022', 'Najafgarh, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL023', 'Narela, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL024', 'Nehru Nagar, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL025', 'North Campus, DU, Delhi - IMD', 'Delhi', 'Delhi', 
            'Active'), ('DL026', 'Okhla Phase-2, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL027', 'Patparganj, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL028', 'Punjabi Bagh, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL029', 'Pusa, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL030', 'Pusa, Delhi - IMD', 'Delhi', 'Delhi', 
            'Active'), ('DL031', 'R K Puram, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL032', 'Rohini, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL033', 'Shadipur, Delhi - CPCB', 'Delhi', 'Delhi', 
            'Active'), ('DL034', 'Sirifort, Delhi - CPCB', 'Delhi', 'Delhi', 
            'Active'), ('DL035', 'Sonia Vihar, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL036', 'Sri Aurobindo Marg, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL037', 'Vivek Vihar, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('DL038', 'Wazirpur, Delhi - DPCC', 'Delhi', 'Delhi', 
            'Active'), ('GJ001', 'Maninagar, Ahmedabad - GPCB', 'Ahmedabad', 'Gujarat', 
            'Active'), ('GJ002', 'GIDC, Ankleshwar - GPCB', 'Ankleshwar', 'Gujarat', 
            'None'), ('GJ003', 'Sector-10, Gandhinagar - GPCB', 'Gandhinagar', 'Gujarat', 
            'None'), ('GJ004', 'GIDC, Nandesari - Nandesari Ind. Association', 'Nandesari', 'Gujarat', 
            'None'), ('GJ005', 'Phase-1 GIDC, Vapi - GPCB', 'Vapi', 'Gujarat', 
            'None'), ('GJ006', 'Phase-4 GIDC, Vatva - GPCB', 'Vatva', 'Gujarat', 
            'None'), ('HR001', 'Patti Mehar, Ambala - HSPCB', 'Ambala', 'Haryana', 
            'Active'), ('HR002', 'Arya Nagar, Bahadurgarh - HSPCB', 'Bahadurgarh', 'Haryana', 
            'Active'), ('HR003', 'Nathu Colony, Ballabgarh - HSPCB', 'Ballabgarh', 'Haryana', 
            'Active'), ('HR004', 'H.B. Colony, Bhiwani - HSPCB', 'Bhiwani', 'Haryana', 
            'Active'), ('HR005', 'Municipal Corporation Office, Dharuhera - HSPCB', 'Dharuhera', 'Haryana', 
            'Active'), ('HR006', 'New Industrial Town, Faridabad - HSPCB', 'Faridabad', 'Haryana', 
            'Active'), ('HR007', 'Sector 11, Faridabad - HSPCB', 'Faridabad', 'Haryana', 
            'Active'), ('HR008', 'Sector 30, Faridabad - HSPCB', 'Faridabad', 'Haryana', 
            'Active'), ('HR009', 'Sector- 16A, Faridabad - HSPCB', 'Faridabad', 'Haryana', 
            'Active'), ('HR010', 'Huda Sector, Fatehabad - HSPCB', 'Fatehabad', 'Haryana', 
            'Active'), ('HR011', 'NISE Gwal Pahari, Gurugram - IMD', 'Gurugram', 'Haryana', 
            'Active'), ('HR012', 'Sector-51, Gurugram - HSPCB', 'Gurugram', 'Haryana', 
            'Active'), ('HR013', 'Teri Gram, Gurugram - HSPCB', 'Gurugram', 'Haryana', 
            'Active'), ('HR014', 'Vikas Sadan, Gurugram - HSPCB', 'Gurugram', 'Haryana', 
            'Active'), ('HR015', 'Urban Estate-II, Hisar - HSPCB', 'Hisar', 'Haryana', 
            'Active'), ('HR016', 'Police Lines, Jind - HSPCB', 'Jind', 'Haryana', 
            'Active'), ('HR017', 'Rishi Nagar, Kaithal - HSPCB', 'Kaithal', 'Haryana', 
            'Active'), ('HR018', 'Sector-12, Karnal - HSPCB', 'Karnal', 'Haryana', 
            'Active'), ('HR019', 'Sector-7, Kurukshetra - HSPCB', 'Kurukshetra', 'Haryana', 
            'Active'), ('HR020', 'General Hospital, Mandikhera - HSPCB', 'Mandikhera', 'Haryana', 
            'Active'), ('HR021', 'Sector-2 IMT, Manesar - HSPCB', 'Manesar', 'Haryana', 
            'Active'), ('HR022', 'Shastri Nagar, Narnaul - HSPCB', 'Narnaul', 'Haryana', 
            'Active'), ('HR023', 'Shyam Nagar, Palwal - HSPCB', 'Palwal', 'Haryana', 
            'Active'), ('HR024', 'Sector-6, Panchkula - HSPCB', 'Panchkula', 'Haryana', 
            'Active'), ('HR025', 'Sector-18, Panipat - HSPCB', 'Panipat', 'Haryana', 
            'Active'), ('HR026', 'MD University, Rohtak - HSPCB', 'Rohtak', 'Haryana', 
            'Active'), ('HR027', 'F-Block, Sirsa - HSPCB', 'Sirsa', 'Haryana', 
            'Active'), ('HR028', 'Murthal, Sonipat - HSPCB', 'Sonipat', 'Haryana', 
            'Active'), ('HR029', 'Gobind Pura, Yamuna Nagar - HSPCB', 'Yamuna Nagar', 'Haryana', 
            'Active'), ('JH001', 'Tata Stadium, Jorapokhar - JSPCB', 'Jorapokhar', 'Jharkhand', 
            'Active'), ('KA001', 'Vidayagiri, Bagalkot - KSPCB', 'Bagalkot', 'Karnataka', 
            'None'), ('KA002', 'BTM Layout, Bengaluru - CPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA003', 'BWSSB Kadabesanahalli, Bengaluru - CPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA004', 'Bapuji Nagar, Bengaluru - KSPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA005', 'City Railway Station, Bengaluru - KSPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA006', 'Hebbal, Bengaluru - KSPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA007', 'Hombegowda Nagar, Bengaluru - KSPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA008', 'Jayanagar 5th Block, Bengaluru - KSPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA009', 'Peenya, Bengaluru - CPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA010', 'Sanegurava Halli, Bengaluru - KSPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA011', 'Silk Board, Bengaluru - KSPCB', 'Bengaluru', 'Karnataka', 
            'Active'), ('KA012', 'Urban, Chamarajanagar - KSPCB', 'Chamarajanagar', 'Karnataka', 
            'None'), ('KA013', 'Chikkaballapur Rural, Chikkaballapur - KSPCB', 'Chikkaballapur', 'Karnataka', 
            'None'), ('KA014', 'Kalyana Nagara, Chikkamagaluru - KSPCB', 'Chikkamagaluru', 'Karnataka', 
            'None'), ('KA015', 'Deshpande Nagar, Hubballi - KSPCB', 'Hubballi', 'Karnataka', 
            'None'), ('KA016', 'Lal Bahadur Shastri Nagar, Kalaburagi - KSPCB', 'Kalaburagi', 'Karnataka', 
            'None'), ('KA017', 'Hebbal 1st Stage, Mysuru - KSPCB', 'Mysuru', 'Karnataka', 
            'None'), ('KA018', 'Vijay Nagar, Ramanagara - KSPCB', 'Ramanagara', 'Karnataka', 
            'None'), ('KA019', 'Ibrahimpur, Vijayapura - KSPCB', 'Vijayapura', 'Karnataka', 
            'None'), ('KA020', 'Collector Office, Yadgir - KSPCB', 'Yadgir', 'Karnataka', 
            'None'), ('KL001', 'Udyogamandal, Eloor - Kerala PCB', 'Eloor', 'Kerala', 
            'None'), ('KL002', 'Kacheripady, Ernakulam - Kerala PCB', 'Ernakulam', 'Kerala', 
            'None'), ('KL003', 'Thavakkara, Kannur - Kerala PCB', 'Kannur', 'Kerala', 
            'None'), ('KL004', 'Vyttila, Kochi - Kerala PCB', 'Kochi', 'Kerala', 
            'None'), ('KL005', 'Polayathode, Kollam - Kerala PCB', 'Kollam', 'Kerala', 
            'None'), ('KL006', 'Palayam, Kozhikode - Kerala PCB', 'Kozhikode', 'Kerala', 
            'None'), ('KL007', 'Kariavattom, Thiruvananthapuram - Kerala PCB', 'Thiruvananthapuram', 'Kerala', 
            'Active'), ('KL008', 'Plammoodu, Thiruvananthapuram - Kerala PCB', 'Thiruvananthapuram', 'Kerala', 
            'Active'), ('MP001', 'T T Nagar, Bhopal - MPPCB', 'Bhopal', 'Madhya Pradesh', 
            'Active'), ('MP002', 'Shrivastav Colony, Damoh - MPPCB', 'Damoh', 'Madhya Pradesh', 
            'None'), ('MP003', 'Bhopal Chauraha, Dewas - MPPCB', 'Dewas', 'Madhya Pradesh', 
            'None'), ('MP004', 'City Center, Gwalior - MPPCB', 'Gwalior', 'Madhya Pradesh', 
            'None'), ('MP005', 'Phool Bagh, Gwalior - Mondelez Ind. Food', 'Gwalior', 'Madhya Pradesh', 
            'None'), ('MP006', 'Chhoti Gwaltoli, Indore - MPPCB', 'Indore', 'Madhya Pradesh', 
            'None'), ('MP007', 'Marhatal, Jabalpur - MPPCB', 'Jabalpur', 'Madhya Pradesh', 
            'None'), ('MP008', 'Gole Bazar, Katni - MPPCB', 'Katni', 'Madhya Pradesh', 
            'None'), ('MP009', 'Sahilara, Maihar - KJS Cements', 'Maihar', 'Madhya Pradesh', 
            'None'), ('MP010', 'Sector-D Industrial Area, Mandideep - MPPCB', 'Mandideep', 'Madhya Pradesh', 
            'None'), ('MP011', 'Sector-2 Industrial Area, Pithampur - MPPCB', 'Pithampur', 'Madhya Pradesh', 
            'None'), ('MP012', 'Shasthri Nagar, Ratlam - IPCA Lab', 'Ratlam', 'Madhya Pradesh', 
            'None'), ('MP013', 'Deen Dayal Nagar, Sagar - MPPCB', 'Sagar', 'Madhya Pradesh', 
            'None'), ('MP014', 'Bandhavgar Colony, Satna - Birla Cement', 'Satna', 'Madhya Pradesh', 
            'None'), ('MP015', 'Vindhyachal STPS, Singrauli - MPPCB', 'Singrauli', 'Madhya Pradesh', 
            'None'), ('MP016', 'Mahakaleshwar Temple, Ujjain - MPPCB', 'Ujjain', 'Madhya Pradesh', 
            'None'), ('MH001', 'More Chowk Waluj, Aurangabad - MPCB', 'Aurangabad', 'Maharashtra', 
            'None'), ('MH002', 'Chandrapur, Chandrapur - MPCB', 'Chandrapur', 'Maharashtra', 
            'None'), ('MH003', 'MIDC Khutala, Chandrapur - MPCB', 'Chandrapur', 'Maharashtra', 
            'None'), ('MH004', 'Khadakpada, Kalyan - MPCB', 'Kalyan', 'Maharashtra', 
            'None'), ('MH005', 'Bandra, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH006', 'Borivali East, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH007', 'Chhatrapati Shivaji Intl. Airport (T2), Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH008', 'Colaba, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH009', 'Kurla, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH010', 'Powai, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH011', 'Sion, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH012', 'Vasai West, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH013', 'Vile Parle West, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH014', 'Worli, Mumbai - MPCB', 'Mumbai', 'Maharashtra', 
            'Active'), ('MH015', 'Opp GPO Civil Lines, Nagpur - MPCB', 'Nagpur', 'Maharashtra', 
            'None'), ('MH016', 'Gangapur Road, Nashik - MPCB', 'Nashik', 'Maharashtra', 
            'None'), ('MH017', 'Airoli, Navi Mumbai - MPCB', 'Navi Mumbai', 'Maharashtra', 
            'None'), ('MH018', 'Mahape, Navi Mumbai - MPCB', 'Navi Mumbai', 'Maharashtra', 
            'None'), ('MH019', 'Nerul, Navi Mumbai - MPCB', 'Navi Mumbai', 'Maharashtra', 
            'None'), ('MH020', 'Karve Road, Pune - MPCB', 'Pune', 'Maharashtra', 
            'None'), ('MH021', 'Solapur, Solapur - MPCB', 'Solapur', 'Maharashtra', 
            'None'), ('MH022', 'Pimpleshwar Mandir, Thane - MPCB', 'Thane', 'Maharashtra', 
            'None'), ('ML001', 'Lumpyngngad, Shillong - Meghalaya PCB', 'Shillong', 'Meghalaya', 
            'Active'), ('MZ001', 'Sikulpuikawn, Aizawl - Mizoram PCB', 'Aizawl', 'Mizoram', 
            'Active'), ('OD001', 'GM Office, Brajrajnagar - OSPCB', 'Brajrajnagar', 'Odisha', 
            'Active'), ('OD002', 'Talcher Coalfields,Talcher - OSPCB', 'Talcher', 'Odisha', 
            'Active'), ('PB001', 'Golden Temple, Amritsar - PPCB', 'Amritsar', 'Punjab', 
            'Active'), ('PB002', 'Hardev Nagar, Bathinda - PPCB', 'Bathinda', 'Punjab', 
            'None'), ('PB003', 'Civil Line, Jalandhar - PPCB', 'Jalandhar', 'Punjab', 
            'None'), ('PB004', 'Kalal Majra, Khanna - PPCB', 'Khanna', 'Punjab', 
            'None'), ('PB005', 'Punjab Agricultural University, Ludhiana - PPCB', 'Ludhiana', 'Punjab', 
            'None'), ('PB006', 'RIMT University, Mandi Gobindgarh - PPCB', 'Gobindgarh', 'Punjab', 
            'None'), ('PB007', 'Model Town, Patiala - PPCB', 'Patiala', 'Punjab', 
            'None'), ('PB008', 'Ratanpura, Rupnagar - Ambuja Cements', 'Rupnagar', 'Punjab', 
            'None'), ('RJ001', 'Moti Doongri, Alwar - RSPCB', 'Alwar', 'Rajasthan', 
            'None'), ('RJ002', 'Civil Lines, Ajmer - RSPCB', 'Ajmer', 'Rajasthan', 
            'None'), ('RJ003', 'RIICO Ind. Area III, Bhiwadi - RSPCB', 'Bhiwandi', 'Rajasthan', 
            'None'), ('RJ004', 'Adarsh Nagar, Jaipur - RSPCB', 'Jaipur', 'Rajasthan', 
            'Active'), ('RJ005', 'Police Commissionerate, Jaipur - RSPCB', 'Jaipur', 'Rajasthan', 
            'Active'), ('RJ006', 'Shastri Nagar, Jaipur - RSPCB', 'Jaipur', 'Rajasthan', 
            'Active'), ('RJ007', 'Collectorate, Jodhpur - RSPCB', 'Jodhpur', 'Rajasthan', 
            'None'), ('RJ008', 'Shrinath Puram, Kota - RSPCB', 'Kota', 'Rajasthan', 
            'None'), ('RJ009', 'Indira Colony Vistar, Pali - RSPCB', 'Pali', 'Rajasthan', 
            'None'), ('RJ010', 'Ashok Nagar, Udaipur - RSPCB', 'Udaipur', 'Rajasthan', 
            'None'), ('TN001', 'Alandur Bus Depot, Chennai - CPCB', 'Chennai', 'Tamil Nadu', 
            'Active'), ('TN002', 'Manali Village, Chennai - TNPCB', 'Chennai', 'Tamil Nadu', 
            'Active'), ('TN003', 'Manali, Chennai - CPCB', 'Chennai', 'Tamil Nadu', 
            'Active'), ('TN004', 'Velachery Res. Area, Chennai - CPCB', 'Chennai', 'Tamil Nadu', 
            'Active'), ('TN005', 'SIDCO Kurichi, Coimbatore - TNPCB', 'Coimbatore', 'Tamil Nadu', 
            'Active'), ('TG001', 'Bollaram Industrial Area, Hyderabad - TSPCB', 'Hyderabad', 'Telangana', 
            'Active'), ('TG002', 'Central University, Hyderabad - TSPCB', 'Hyderabad', 'Telangana', 
            'Active'), ('TG003', 'ICRISAT Patancheru, Hyderabad - TSPCB', 'Hyderabad', 'Telangana', 
            'Active'), ('TG004', 'IDA Pashamylaram, Hyderabad - TSPCB', 'Hyderabad', 'Telangana', 
            'Active'), ('TG005', 'Sanathnagar, Hyderabad - TSPCB', 'Hyderabad', 'Telangana', 
            'Active'), ('TG006', 'Zoo Park, Hyderabad - TSPCB', 'Hyderabad', 'Telangana', 
            'Active'), ('UP001', 'Sanjay Palace, Agra - UPPCB', 'Agra', 'Uttar Pradesh', 
            'None'), ('UP002', 'New Collectorate, Baghpat - UPPCB', 'Baghpat', 'Uttar Pradesh', 
            'None'), ('UP003', 'Yamunapuram, Bulandshahr - UPPCB', 'Bulandshahr', 'Uttar Pradesh', 
            'None'), ('UP004', 'Indirapuram, Ghaziabad - UPPCB', 'Ghaziabad', 'Uttar Pradesh', 
            'None'), ('UP005', 'Loni, Ghaziabad - UPPCB', 'Ghaziabad', 'Uttar Pradesh', 
            'None'), ('UP006', 'Sanjay Nagar, Ghaziabad - UPPCB', 'Ghaziabad', 'Uttar Pradesh', 
            'None'), ('UP007', 'Vasundhara, Ghaziabad - UPPCB', 'Ghaziabad', 'Uttar Pradesh', 
            'None'), ('UP008', 'Knowledge Park - III, Greater Noida - UPPCB', 'Greater Noida', 'Uttar Pradesh', 
            'None'), ('UP009', 'Knowledge Park - V, Greater Noida - UPPCB', 'Greater Noida', 'Uttar Pradesh', 
            'None'), ('UP010', 'Anand Vihar, Hapur - UPPCB', 'Hapur', 'Uttar Pradesh', 
            'None'), ('UP011', 'Nehru Nagar, Kanpur - UPPCB', 'Kanpur', 'Uttar Pradesh', 
            'None'), ('UP012', 'Central School, Lucknow - CPCB', 'Lucknow', 'Uttar Pradesh', 
            'Active'), ('UP013', 'Gomti Nagar, Lucknow - UPPCB', 'Lucknow', 'Uttar Pradesh', 
            'Active'), ('UP014', 'Lalbagh, Lucknow - CPCB', 'Lucknow', 'Uttar Pradesh', 
            'Active'), ('UP015', 'Nishant Ganj, Lucknow - UPPCB', 'Lucknow', 'Uttar Pradesh', 
            'Inactive'), ('UP016', 'Talkatora District Industries Center, Lucknow - CPCB', 'Lucknow', 'Uttar Pradesh', 
            'Active'), ('UP017', 'Ganga Nagar, Meerut - UPPCB', 'Meerut', 'Uttar Pradesh', 
            'None'), ('UP018', 'Jai Bhim Nagar, Meerut - UPPCB', 'Meerut', 'Uttar Pradesh', 
            'None'), ('UP019', 'Pallavpuram Phase 2, Meerut - UPPCB', 'Meerut', 'Uttar Pradesh', 
            'None'), ('UP020', 'Lajpat Nagar, Moradabad - UPPCB', 'Moradabad', 'Uttar Pradesh', 
            'None'), ('UP021', 'New Mandi, Muzaffarnagar - UPPCB', 'Muzzaffarnagar', 'Uttar Pradesh', 
            'None'), ('UP022', 'Sector - 125, Noida - UPPCB', 'Noida', 'Uttar Pradesh', 
            'None'), ('UP023', 'Sector - 62, Noida - IMD', 'Noida', 'Uttar Pradesh', 
            'None'), ('UP024', 'Sector-1, Noida - UPPCB', 'Noida', 'Uttar Pradesh', 
            'None'), ('UP025', 'Sector-116, Noida - UPPCB', 'Noida', 'Uttar Pradesh', 
            'None'), ('UP026', 'Ardhali Bazar, Varanasi - UPPCB', 'Varanasi', 'Uttar Pradesh', 
            'None'), ('WB001', 'Asansol Court Area, Asansol - WBPCB', 'Asansol', 'West Bengal', 
            'None'), ('WB002', 'Sidhu Kanhu Indoor Stadium, Durgapur - WBPCB', 'Durgapur', 'West Bengal', 
            'None'), ('WB003', 'Haldia, Haldia - WBPCB', 'Haldia', 'West Bengal', 
            'None'), ('WB004', 'Belur Math, Howrah - WBPCB', 'Howrah', 'West Bengal', 
            'None'), ('WB005', 'Ghusuri, Howrah - WBPCB', 'Howrah', 'West Bengal', 
            'None'), ('WB006', 'Padmapukur, Howrah - WBPCB', 'Howrah', 'West Bengal', 
            'None'), ('WB007', 'Ballygunge, Kolkata - WBPCB', 'Kolkata', 'West Bengal', 
            'Active'), ('WB008', 'Bidhannagar, Kolkata - WBPCB', 'Kolkata', 'West Bengal', 
            'Active'), ('WB009', 'Fort William, Kolkata - WBPCB', 'Kolkata', 'West Bengal', 
            'Active'), ('WB010', 'Jadavpur, Kolkata - WBPCB', 'Kolkata', 'West Bengal', 
            'Active'), ('WB011', 'Rabindra Bharati University, Kolkata - WBPCB', 'Kolkata', 'West Bengal', 
            'Active'), ('WB012', 'Rabindra Sarobar, Kolkata - WBPCB', 'Kolkata', 'West Bengal', 
            'Active'), ('WB013', 'Victoria, Kolkata - WBPCB', 'Kolkata', 'West Bengal', 
            'Active'), ('WB014', 'Ward-32 Bapupara, Siliguri - WBPCB', 'Siliguri', 'West Bengal', 
            'None');